import { RefreshCw, Send } from "lucide-react";
import { useEffect, useState } from "react";
import { createIssue, fetchInventory, fetchIssues, fetchVendors } from "../lib/api";

const blank = { itemCode: "", quantity: "", unit: "kg", department: "", vendorId: "", unitCost: "", date: "", notes: "" };
function Issues() {
  const [inventory, setInventory] = useState([]); const [vendors, setVendors] = useState([]); const [issues, setIssues] = useState([]); const [form, setForm] = useState(blank); const [error, setError] = useState("");
  async function load() { try { const [items, supplierList, records] = await Promise.all([fetchInventory(), fetchVendors(), fetchIssues()]); setInventory(items); setVendors(supplierList); setIssues(records.reverse()); } catch (loadError) { setError(loadError.message); } }
  useEffect(() => { Promise.resolve().then(load); }, []);
  function set(field, value) { setForm((current) => ({ ...current, [field]: value })); }
  const selected = inventory.find((item) => item.itemCode === form.itemCode); const cost = Number(form.unitCost || selected?.lastPurchasePrice || selected?.unitPrice || 0); const total = Number(form.quantity || 0) * cost;
  async function submit(event) { event.preventDefault(); setError(""); try { await createIssue({ ...form, unit: form.unit || selected?.unit, unitCost: cost, quantity: Number(form.quantity) }); setForm(blank); load(); } catch (saveError) { setError(saveError.message); } }
  return <section><div className="page-heading"><div><span className="eyebrow">OUTBOUND LEDGER</span><h2>Stock Issues</h2><p>Record what each department receives and the cost of consumption.</p></div><button className="ghost-button" onClick={load}><RefreshCw size={16} /> Refresh</button></div><div className="table-panel"><form className="form-grid" onSubmit={submit} style={{ padding: "22px 0" }}><label>Item<select required value={form.itemCode} onChange={(event) => { const item = inventory.find((entry) => entry.itemCode === event.target.value); set("itemCode", event.target.value); if (item) { set("unit", item.unit); set("unitCost", item.lastPurchasePrice || item.unitPrice || 0); } }}>{inventory.map((item) => <option value={item.itemCode} key={item.itemCode}>{item.itemCode} - {item.name} ({item.quantity} {item.unit})</option>)}</select></label><label>Receiving department<input required value={form.department} onChange={(event) => set("department", event.target.value)} placeholder="Kitchen" /></label><label>Quantity<input required type="number" min="0.001" step="any" value={form.quantity} onChange={(event) => set("quantity", event.target.value)} /></label><label>Unit cost (₹)<input required type="number" min="0" step="any" value={form.unitCost} onChange={(event) => set("unitCost", event.target.value)} /></label><label>Source vendor<select value={form.vendorId} onChange={(event) => set("vendorId", event.target.value)}><option value="">Inventory source</option>{vendors.map((vendor) => <option value={vendor.vendorId} key={vendor.vendorId}>{vendor.vendorName}</option>)}</select></label><label>Date<input type="date" value={form.date} onChange={(event) => set("date", event.target.value)} /></label><label>Notes<input value={form.notes} onChange={(event) => set("notes", event.target.value)} /></label><div><small>Issue value</small><strong style={{ display: "block", marginTop: 8 }}>₹{total.toLocaleString()}</strong></div><button className="primary-button compact" type="submit"><Send size={16} /> Record issue</button></form>{error && <div className="form-error">{error}</div>}</div><div className="table-panel" style={{ marginTop: 24 }}><div className="table-toolbar"><h3>Issue transactions <span>{issues.length}</span></h3></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Item</th><th>Department</th><th>Quantity</th><th>Unit cost</th><th>Total</th></tr></thead><tbody>{issues.map((issue) => <tr key={issue.issueId}><td>{issue.date}</td><td><strong>{issue.itemName}</strong><small>{issue.itemCode}</small></td><td>{issue.department}</td><td>{issue.quantity} {issue.unit}</td><td>₹{issue.unitCost.toLocaleString()}</td><td><strong>₹{issue.totalIssueValue.toLocaleString()}</strong></td></tr>)}</tbody></table></div></div></section>;
}
export default Issues;
