import { Plus, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { createPurchase, fetchInventory, fetchPurchases, fetchVendors } from "../lib/api";

const blank = { itemCode: "", vendorId: "", quantity: "", unitPrice: "", unit: "kg", date: "" };
function Purchases() {
  const [inventory, setInventory] = useState([]); const [vendors, setVendors] = useState([]); const [purchases, setPurchases] = useState([]); const [form, setForm] = useState(blank); const [error, setError] = useState("");
  async function load() { try { const [items, supplierList, records] = await Promise.all([fetchInventory(), fetchVendors(), fetchPurchases()]); setInventory(items); setVendors(supplierList); setPurchases(records.reverse()); } catch (loadError) { setError(loadError.message); } }
  useEffect(() => { Promise.resolve().then(load); }, []);
  function set(field, value) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event) { event.preventDefault(); setError(""); try { await createPurchase({ ...form, quantity: Number(form.quantity), unitPrice: Number(form.unitPrice) }); setForm(blank); load(); } catch (saveError) { setError(saveError.message); } }
  const total = Number(form.quantity || 0) * Number(form.unitPrice || 0);
  return <section><div className="page-heading"><div><span className="eyebrow">INBOUND LEDGER</span><h2>Purchases</h2><p>Record every receipt and preserve the price paid to each vendor.</p></div><button className="ghost-button" onClick={load}><RefreshCw size={16} /> Refresh</button></div><div className="table-panel"><form className="form-grid" onSubmit={submit} style={{ padding: "22px 0" }}><label>Item<select required value={form.itemCode} onChange={(event) => { const item = inventory.find((entry) => entry.itemCode === event.target.value); set("itemCode", event.target.value); if (item) set("unit", item.unit); }}>{inventory.map((item) => <option value={item.itemCode} key={item.itemCode}>{item.itemCode} - {item.name}</option>)}</select></label><label>Vendor<select required value={form.vendorId} onChange={(event) => set("vendorId", event.target.value)}><option value="">Select vendor</option>{vendors.filter((vendor) => vendor.active).map((vendor) => <option value={vendor.vendorId} key={vendor.vendorId}>{vendor.vendorName}</option>)}</select></label><label>Quantity<input required type="number" min="0.001" step="any" value={form.quantity} onChange={(event) => set("quantity", event.target.value)} /></label><label>Unit price (₹)<input required type="number" min="0" step="any" value={form.unitPrice} onChange={(event) => set("unitPrice", event.target.value)} /></label><label>Unit<select value={form.unit} onChange={(event) => set("unit", event.target.value)}><option>kg</option><option>g</option><option>L</option><option>ml</option><option>unit</option></select></label><label>Date<input type="date" value={form.date} onChange={(event) => set("date", event.target.value)} /></label><div><small>Calculated purchase value</small><strong style={{ display: "block", marginTop: 8 }}>₹{total.toLocaleString()}</strong></div><button className="primary-button compact" type="submit"><Plus size={16} /> Record purchase</button></form>{error && <div className="form-error">{error}</div>}</div><div className="table-panel" style={{ marginTop: 24 }}><div className="table-toolbar"><h3>Purchase transactions <span>{purchases.length}</span></h3></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Item</th><th>Vendor</th><th>Quantity</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{purchases.map((purchase) => <tr key={purchase.purchaseId}><td>{purchase.date}</td><td><strong>{purchase.itemName}</strong><small>{purchase.itemCode}</small></td><td>{purchase.vendorName}</td><td>{purchase.quantity} {purchase.unit}</td><td>₹{purchase.unitPrice.toLocaleString()}</td><td><strong>₹{purchase.totalPurchaseCost.toLocaleString()}</strong></td></tr>)}</tbody></table></div></div></section>;
}
export default Purchases;
