import { Pencil, Plus, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { createVendor, fetchVendorReport, updateVendor } from "../lib/api";

const blank = { vendorName: "", contactPerson: "", phone: "", email: "", address: "" };
function Vendors() {
  const [report, setReport] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  async function load() { try { const summary = await fetchVendorReport(); setReport(summary.vendors); } catch (loadError) { setError(loadError.message); } }
  useEffect(() => { Promise.resolve().then(load); }, []);
  function set(field, value) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event) { event.preventDefault(); try { if (editing) await updateVendor(editing, form); else await createVendor(form); setForm(blank); setEditing(null); load(); } catch (saveError) { setError(saveError.message); } }
  const visible = report.filter((vendor) => vendor.vendorName.toLowerCase().includes(query.toLowerCase()));
  return <section><div className="page-heading"><div><span className="eyebrow">SUPPLIER MASTER</span><h2>Vendors</h2><p>Keep supplier contacts, supplied items, and paid prices together.</p></div><button className="ghost-button" onClick={load}><RefreshCw size={16} /> Refresh</button></div><div className="table-panel"><form className="form-grid" onSubmit={submit} style={{ padding: "22px 0" }}><label>Vendor name<input required value={form.vendorName} onChange={(event) => set("vendorName", event.target.value)} /></label><label>Contact person<input value={form.contactPerson} onChange={(event) => set("contactPerson", event.target.value)} /></label><label>Phone<input value={form.phone} onChange={(event) => set("phone", event.target.value)} /></label><label>Email<input type="email" value={form.email} onChange={(event) => set("email", event.target.value)} /></label><label>Address<input value={form.address} onChange={(event) => set("address", event.target.value)} /></label><button className="primary-button compact" type="submit">{editing ? <Pencil size={16} /> : <Plus size={16} />}{editing ? "Update vendor" : "Add vendor"}</button></form>{error && <div className="form-error">{error}</div>}</div><div className="table-panel" style={{ marginTop: 24 }}><div className="table-toolbar"><h3>Vendor list <span>{visible.length}</span></h3><label className="search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search vendors" /></label></div><div className="table-scroll"><table><thead><tr><th>Vendor</th><th>Items supplied</th><th>Purchase quantity</th><th>Purchase value</th><th>Average price</th><th>Last purchase</th><th /></tr></thead><tbody>{visible.map((vendor) => <tr key={vendor.vendorId}><td><strong>{vendor.vendorName}</strong><small>{vendor.contactPerson || vendor.phone || "No contact added"}</small></td><td>{vendor.items.join(", ") || "No purchases yet"}</td><td>{vendor.purchaseQuantity || 0}</td><td>₹{Number(vendor.purchaseValue || 0).toLocaleString()}</td><td>₹{Number(vendor.averagePurchasePrice || 0).toFixed(2)}</td><td>{vendor.lastPurchaseDate || "-"}</td><td><button className="icon-button" onClick={() => { setEditing(vendor.vendorId); setForm(vendor); }} aria-label={`Edit ${vendor.vendorName}`}><Pencil size={16} /></button></td></tr>)}</tbody></table></div></div></section>;
}
export default Vendors;
